name: aura_wallpapers
description: A premium Android live wallpaper app with native wallpaper engine integration.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  video_player: ^2.9.5
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wallpapers/football/thumbs/
    - assets/wallpapers/football/sources/
    - assets/wallpapers/anime/thumbs/
    - assets/wallpapers/anime/sources/
    - assets/wallpapers/gaming/thumbs/
    - assets/wallpapers/gaming/sources/
